
BugGrabberDB = {
	["session"] = 8,
	["lastSanitation"] = 3,
	["errors"] = {
		{
			["message"] = "[string \"--[==[ Error in 'Extraction du mal':'custom...\"]:11: attempt to perform arithmetic on global 'valByOrbs' (a nil value)",
			["time"] = "2020/05/07 19:41:22",
			["stack"] = "[string \"=[C]\"]: in function `xpcall'\n[string \"@Interface\\AddOns\\WeakAuras\\WeakAuras-2.17.4.lua\"]:6253: in function `RunCustomTextFunc'\n[string \"@Interface\\AddOns\\WeakAuras\\SubRegionTypes\\SubText.lua\"]:264: in function `?'\n[string \"@Interface\\AddOns\\WeakAuras\\RegionTypes\\RegionPrototype.lua\"]:33: in function `Notify'\n[string \"@Interface\\AddOns\\WeakAuras\\WeakAuras-2.17.4.lua\"]:6031: in function <Interface\\AddOns\\WeakAuras\\WeakAuras.lua:6028>\n[string \"@Interface\\AddOns\\WeakAuras\\WeakAuras-2.17.4.lua\"]:6114: in function <Interface\\AddOns\\WeakAuras\\WeakAuras.lua:6081>\n[string \"@Interface\\AddOns\\WeakAuras\\WeakAuras-2.17.4.lua\"]:6198: in function `UpdatedTriggerState'\n[string \"@Interface\\AddOns\\WeakAuras\\WeakAuras-2.17.4.lua\"]:5968: in function `UpdateFakeStatesFor'\n[string \"@Interface\\AddOns\\WeakAuras\\WeakAuras-2.17.4.lua\"]:5941: in function `FakeStatesFor'\n[string \"@Interface\\AddOns\\WeakAurasOptions\\AceGUI-Widgets\\AceGUIWidget-WeakAurasDisplayButton.lua\"]:1866: in function `PriorityShow'\n[string \"@Interface\\AddOns\\WeakAurasOptions\\AceGUI-Widgets\\AceGUIWidget-WeakAurasDisplayButton.lua\"]:1659: in function `PriorityShow'\n[string \"@Interface\\AddOns\\WeakAurasOptions\\OptionsFrames\\OptionsFrame.lua\"]:988: in function `finishPicking'\n[string \"@Interface\\AddOns\\WeakAurasOptions\\OptionsFrames\\OptionsFrame.lua\"]:1011: in function `PickDisplay'\n[string \"@Interface\\AddOns\\WeakAurasOptions\\WeakAurasOptions-2.17.4.lua\"]:4275: in function <...terface\\AddOns\\WeakAurasOptions\\WeakAurasOptions.lua:4274>\n[string \"=(tail call)\"]: ?",
			["session"] = 1,
			["counter"] = 1,
		}, -- [1]
		{
			["message"] = "[string \"--[==[ Error in 'PhoGuild - Raid Ability Ti...\"]:4: bad argument #1 to 'strtrim' (string expected, got nil)",
			["time"] = "2020/05/07 19:40:00",
			["stack"] = "[string \"--[==[ Error in 'PhoGuild - Raid Ability Timeline Icon':'custom text' ]==] return function()\n    if not aura_env.state then return end\n    local text = aura_env.state.name\n    text = strtrim(text) -- Trim\n    local inlineIconAdjust = string.len(string.match(text,\"|T.-|t\") or \"\")\n    if inlineIconAdjust > 0 then inlineIconAdjust = inlineIconAdjust - 2 end -- Make icons take 2 characters.\n    if (aura_env.config.textMaxLength or 0)>=5 and text:len()-inlineIconAdjust>aura_env.config.textMaxLength then\n        text = string.sub(text,1,aura_env.config.textMaxLength+inlineIconAdjust-2)..\"..\" -- Truncate\n    end\n    if aura_env.state.colorTable then\n        local t=aura_env.state.colorTable\n        text = string.format(\"\\124c%02x%02x%02x%02x%s\\124r\",255*(t[4] or 1),255*(t[1] or 0),255*(t[2] or 0),255*(t[3] or 0),text)\n    end\n    return text\nend\"]:4: in function <[string \"--[==[ Error in 'PhoGuild - Raid Ability Ti...\"]:1>\n[string \"=[C]\"]: in function `xpcall'\n[string \"@Interface\\AddOns\\WeakAuras\\WeakAuras-2.17.4.lua\"]:6253: in function `RunCustomTextFunc'\n[string \"@Interface\\AddOns\\WeakAuras\\SubRegionTypes\\SubText.lua\"]:264: in function `?'\n[string \"@Interface\\AddOns\\WeakAuras\\RegionTypes\\RegionPrototype.lua\"]:33: in function `Notify'\n[string \"@Interface\\AddOns\\WeakAuras\\WeakAuras-2.17.4.lua\"]:6031: in function <Interface\\AddOns\\WeakAuras\\WeakAuras.lua:6028>\n[string \"@Interface\\AddOns\\WeakAuras\\WeakAuras-2.17.4.lua\"]:6114: in function <Interface\\AddOns\\WeakAuras\\WeakAuras.lua:6081>\n[string \"@Interface\\AddOns\\WeakAuras\\WeakAuras-2.17.4.lua\"]:6198: in function `UpdatedTriggerState'\n[string \"@Interface\\AddOns\\WeakAuras\\WeakAuras-2.17.4.lua\"]:5968: in function `UpdateFakeStatesFor'\n[string \"@Interface\\AddOns\\WeakAuras\\WeakAuras-2.17.4.lua\"]:5941: in function `FakeStatesFor'\n[string \"@Interface\\AddOns\\WeakAurasOptions\\AceGUI-Widgets\\AceGUIWidget-WeakAurasDisplayButton.lua\"]:1866: in function `PriorityShow'\n[string \"@Interface\\AddOns\\WeakAurasOptions\\AceGUI-Widgets\\AceGUIWidget-WeakAurasDisplayButton.lua\"]:1659: in function `PriorityShow'\n[string \"@Interface\\AddOns\\WeakAurasOptions\\WeakAurasOptions-2.17.4.lua\"]:1609: in function <...terface\\AddOns\\WeakAurasOptions\\WeakAurasOptions.lua:1574>",
			["session"] = 7,
			["counter"] = 11,
		}, -- [2]
	},
}
